// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOmjUKr4AMXKXknlZN4cxikZ1OV-VzdTw',
    appId: '1:965197810926:web:b31a44ba0b5ce6653737ff',
    messagingSenderId: '965197810926',
    projectId: 'data-groupe-h31',
    authDomain: 'data-groupe-h31.firebaseapp.com',
    storageBucket: 'data-groupe-h31.firebasestorage.app',
    measurementId: 'G-WJVG986WF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBifq8aWgryI-Mx4snlqBj8kL-26C0yBUg',
    appId: '1:965197810926:android:8f1d2cd0b5da56483737ff',
    messagingSenderId: '965197810926',
    projectId: 'data-groupe-h31',
    storageBucket: 'data-groupe-h31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUQ5CmvGzezL0z9OsQWvIbFF9HaghJKAI',
    appId: '1:965197810926:ios:406ebc632383def93737ff',
    messagingSenderId: '965197810926',
    projectId: 'data-groupe-h31',
    storageBucket: 'data-groupe-h31.firebasestorage.app',
    iosBundleId: 'com.example.home32',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUQ5CmvGzezL0z9OsQWvIbFF9HaghJKAI',
    appId: '1:965197810926:ios:406ebc632383def93737ff',
    messagingSenderId: '965197810926',
    projectId: 'data-groupe-h31',
    storageBucket: 'data-groupe-h31.firebasestorage.app',
    iosBundleId: 'com.example.home32',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOmjUKr4AMXKXknlZN4cxikZ1OV-VzdTw',
    appId: '1:965197810926:web:87bd393dff3b8d723737ff',
    messagingSenderId: '965197810926',
    projectId: 'data-groupe-h31',
    authDomain: 'data-groupe-h31.firebaseapp.com',
    storageBucket: 'data-groupe-h31.firebasestorage.app',
    measurementId: 'G-6P61ZH98Z3',
  );
}
