// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4yaqpBayfg03tMbrJp32odstJShIoPK4',
    appId: '1:465543942574:web:c17a79ef88245d5b25f83f',
    messagingSenderId: '465543942574',
    projectId: 'hw32-6bc34',
    authDomain: 'hw32-6bc34.firebaseapp.com',
    storageBucket: 'hw32-6bc34.firebasestorage.app',
    measurementId: 'G-32SBCMME4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVMIPg4BbNu_XdkwDUq5XGQ9ecE90WCHQ',
    appId: '1:465543942574:android:24a6f91dba2f734025f83f',
    messagingSenderId: '465543942574',
    projectId: 'hw32-6bc34',
    storageBucket: 'hw32-6bc34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP1HBi1ZhsDEjG9TOqtoRsCo2W3TIHHW4',
    appId: '1:465543942574:ios:fe16fe0242d6e83d25f83f',
    messagingSenderId: '465543942574',
    projectId: 'hw32-6bc34',
    storageBucket: 'hw32-6bc34.firebasestorage.app',
    iosBundleId: 'com.example.homeWork31',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP1HBi1ZhsDEjG9TOqtoRsCo2W3TIHHW4',
    appId: '1:465543942574:ios:fe16fe0242d6e83d25f83f',
    messagingSenderId: '465543942574',
    projectId: 'hw32-6bc34',
    storageBucket: 'hw32-6bc34.firebasestorage.app',
    iosBundleId: 'com.example.homeWork31',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4yaqpBayfg03tMbrJp32odstJShIoPK4',
    appId: '1:465543942574:web:533095d248d2581025f83f',
    messagingSenderId: '465543942574',
    projectId: 'hw32-6bc34',
    authDomain: 'hw32-6bc34.firebaseapp.com',
    storageBucket: 'hw32-6bc34.firebasestorage.app',
    measurementId: 'G-MR3Z6MSSVQ',
  );
}
